services:
  inforce-app:
    build:
      context: ../../inforce/
      dockerfile: Dockerfile
    container_name: inforce-app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SENTRY_DSN=${SENTRY_DSN}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "8000:8000"
    restart: unless-stopped
    expose:
      - 8000
    command: ["poetry", "run", "gunicorn", "--workers", "1", "core.project.wsgi:application", "--bind", "0.0.0.0:8000"]
    depends_on:
      - postgres
    volumes:
      - ..:/inforce/
    networks:
      - ppostgres.network

networks:
  ppostgres.network:
    driver: bridge
