# Generated by Django 5.0.6 on 2025-02-19 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('role', models.CharField(choices=[('chef', 'Chef'), ('waiter', 'Waiter')], max_length=50)),
            ],
            options={
                'verbose_name': 'Співробітники',
                'verbose_name_plural': 'Співробітники',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='MenuView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата перегляду')),
            ],
            options={
                'verbose_name': 'Перегляд меню',
                'verbose_name_plural': 'Перегляди меню',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('title', models.CharField(max_length=50, verbose_name='Назва Ресторану')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Ресторани',
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('weekday', models.CharField(max_length=50, verbose_name='День Тижня')),
                ('morning', models.CharField(max_length=50, verbose_name='Ранок')),
                ('afternoon', models.CharField(max_length=50, verbose_name='Опівдні')),
                ('evening', models.CharField(max_length=50, verbose_name='Вечір')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'db_table': 'menu',
            },
        ),
    ]
